### ISSUE TITLE
Can`t install hnswlib-node

### ISSUE THREAD

**Issue by blozixdextr** [yoshoku/hnswlib-node#46]
Please help to install...
![image](https://user-images.githubusercontent.com/2786905/220911392-125b617e-4268-4440-becf-a5705e11b0a3.png)

**Comment by yoshoku** [comment]
@blozixdextr `langchainjs` seems to use `yarn` as package manager. Perhaps the error can be avoided by using yarn:

```sh
$ npm install -g yarn
$ yarn install
```

Or remove the `workspaces` property from the `package.json`, and then install it using npm:

```sh
$ git diff package.json
```
```diff
- "workspaces": [
-   "langchain",
-   "examples",
-   "docs",
-   "test-exports"
- ],
```
```
$ npm install hnswlib-node
```

**Comment by yoshoku** [comment]
@blozixdextr I will close this issue since the duplicate issue is on the langchainjs: https://github.com/hwchase17/langchainjs/issues/113
