### ISSUE TITLE
Invalid ELF Header - AWS Lambda

### ISSUE THREAD

**Issue by zammitjames** [yoshoku/hnswlib-node#55]
When trying to use the library on AWS Lambda, I'm getting the following error:

`"/var/task/node_modules/hnswlib-node/build/Release/addon.node: invalid ELF header"`. 

It looks like it's a binding issue?

**Comment by yoshoku** [comment]
@zammitjames hnswlib-node is a native addon module using node-addon-api. To run it on AWS Lambda, I think you need to build it with an Amazon Linux docker image and deploy the zip file including the node_modules directory.

**Comment by zammitjames** [comment]
Makes sense - thank you!
