### ISSUE TITLE
HNSWLib-node not found when using in a AWS Lambda function

### ISSUE THREAD

**Issue by joaotextor** [yoshoku/hnswlib-node#77]
I recently made a simple Typescript function to create a VectorStore using HNSWLib-node.
It saves the vector store in a folder and then, in another script file, I load and execute a RetrievalQAChain using OpenAI.

Everything was working fine until I decided to put that in a AWS Lambda Function.

My package.json has the following dependencies:
```
    "hnswlib-node": "^1.4.2",
    "langchain": "^0.0.59",

```
Also, I double checked and the hnswlib-node folder is inside "node_modules" folder in my lambda function folder.

However, I keep getting the following error (from CloudWatch Logs):
```
ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Please install hnswlib-node as a dependency with,
 e.g. `npm install -S hnswlib-node`",
    "stack":["Error: Please install hnswlib-node as a dependency with, e.g. `npm install -S hnswlib-node`","    
    at Function.imports (/var/task/node_modules/langchain/dist/vectorstores/hnswlib.cjs:161:19)","
    at async Function.getHierarchicalNSW (/var/task/node_modules/langchain/dist/vectorstores/hnswlib.cjs:38:37)","
    at async Function.load (/var/task/node_modules/langchain/dist/vectorstores/hnswlib.cjs:123:23)"," 
    at async AMCompanion (/var/task/index.js:18:29)","    at async Runtime.exports.handler (/var/task/index.js:39:22)"]}
```

Also, this error is not thrown on importing HNSWLib, but only in the following line of code:

```
const vectorStore = await HNSWLib.load("data", new OpenAIEmbeddings(
            {
                openAIApiKey: process.env.OPENAI_API_KEY,
            } 
        ))
```

This is my import:

`const { HNSWLib } = require("langchain/vectorstores/hnswlib")`

It seems I'm not the only one with this problem. See [this post](https://github.com/hwchase17/langchain/issues/1364#issuecomment-1517134074)

**Expeted behavior:** code would be executed properly, just like when executed on my local machine.

**Actual behavior:** the error pasted above.

**Comment by yoshoku** [comment]
@joaotextor 
hnswlib-node is a native module using node-addon-api. I think that you need to deploy a container image includes hnswlib-node to AWS Lambda. The steps are summarized in the Wiki below:

https://github.com/yoshoku/hnswlib-node/wiki/hnswlib-node-on-AWS-Lambda

**Comment by joaotextor** [comment]
> @joaotextor hnswlib-node is a native module using node-addon-api. I think that you need to deploy a container image includes hnswlib-node to AWS Lambda. The steps are summarized in the Wiki below:
> 
> https://github.com/yoshoku/hnswlib-node/wiki/hnswlib-node-on-AWS-Lambda

The answer I was looking for. Thank you so much!

**Comment by yoshoku** [comment]
I have changed the title of the wiki page and added a link to the page on the README. Thank you for your understanding.
https://github.com/yoshoku/hnswlib-node/wiki/How-to-run-hnswlib-node-on-AWS-Lambda
https://github.com/yoshoku/hnswlib-node/commit/92cc80ca7f5a43a102e1de111fcf0592e8dc09ae
